; Trie with Insert, Search and Full Delete (8086 - MASM/TASM style)
; Each node is 53 bytes: [0] IS_END (byte), [1..52] child pointers for 'A'..'Z' (26 words = 52 bytes)
.MODEL SMALL
.STACK 200H
.DATA
; configuration
MAX_NODES EQU 10
NODE_SIZE EQU 53 ; 1 + 52
MAX_DEPTH EQU 64 ; max word length
TRIE_MEM DB MAX_NODES * NODE_SIZE DUP(0)
NODE_COUNT DW 0
PATH_NODES DW MAX_DEPTH DUP(0)
PATH_CHARS DB MAX_DEPTH DUP(0)
PATH_SP DB 0
WORD1 DB 'CAT$'
WORD2 DB 'KIT$'
MSG_INSERTED DB 'Inserted: $'
MSG_FOUND DB 'Found: $'
MSG_NOTFOUND DB 'Not Found: $'
MSG_DELETED DB 'Deleted: $'
NEWLINE DB 0DH,0AH,'$'
.CODE
CREATE_NODE PROC
    PUSH BX
    PUSH CX
    PUSH DI
    MOV AX, NODE_COUNT
    CMP AX, MAX_NODES
    JGE NODE_FULL
    MOV BX, NODE_SIZE
    MUL BX
    MOV DI, OFFSET TRIE_MEM
    ADD DI, AX
    MOV CX, NODE_SIZE
    XOR AL, AL
    REP STOSB
    INC NODE_COUNT
    SUB DI, NODE_SIZE
    MOV AX, DI
    SUB AX, OFFSET TRIE_MEM ; return relative offset
    JMP CN_DONE
NODE_FULL:
    XOR AX, AX
CN_DONE:
    POP DI
    POP CX
    POP BX
    RET
CREATE_NODE ENDP
GET_CHILD PROC
    PUSH BX
    PUSH SI
    SUB AL, 'A'
    CMP AL, 25
    JA GC_NO_CHILD
    MOV BL, AL
    XOR BH, BH
    SHL BX, 1
    MOV SI, BP
    ADD SI, 1
    ADD SI, BX
    MOV AX, [SI]
    JMP GC_DONE
GC_NO_CHILD:
    XOR AX, AX
GC_DONE:
    POP SI
    POP BX
    RET
GET_CHILD ENDP
SET_CHILD PROC
    PUSH BX
    PUSH SI
    SUB AL, 'A'
    CMP AL, 25
    JA SC_DONE
    MOV BL, AL
    XOR BH, BH
    SHL BX, 1
    MOV SI, BP
    ADD SI, 1
    ADD SI, BX
    MOV [SI], DX
SC_DONE:
    POP SI
    POP BX
    RET
SET_CHILD ENDP
HAS_CHILD PROC
    PUSH CX
    PUSH SI
    XOR AX, AX
    MOV CX, 26
    MOV SI, BP
    ADD SI, 1
HC_LOOP:
    OR AX, [SI]
    ADD SI, 2
    LOOP HC_LOOP
    POP SI
    POP CX
    RET
HAS_CHILD ENDP
PUSH_PATH PROC
    PUSH SI
    MOV BX, OFFSET PATH_SP
    MOV SI, [BX]
    CMP SI, MAX_DEPTH
    JAE PP_DONE
    MOV DI, OFFSET PATH_NODES
    SHL SI, 1
    ADD DI, SI
    MOV [DI], AX
    MOV DI, OFFSET PATH_CHARS
    MOV SI, [BX]
    ADD DI, SI
    MOV [DI], DL ; DL = char index
    INC BYTE PTR [BX]
PP_DONE:
    POP SI
    RET
PUSH_PATH ENDP
POP_PATH PROC
    PUSH SI
    MOV BX, OFFSET PATH_SP
    MOV SI, [BX]
    CMP SI, 0
    JE POP_EMPTY
    DEC SI
    MOV [BX], SI
    MOV DI, OFFSET PATH_NODES
    SHL SI, 1
    ADD DI, SI
    MOV AX, [DI]
    MOV DI, OFFSET PATH_CHARS
    MOV SI, [BX]
    ADD DI, SI
    MOV BL, [DI]
    JMP POP_DONE
POP_EMPTY:
    XOR AX, AX
    XOR BL, BL
POP_DONE:
    POP SI
    RET
POP_PATH ENDP
INSERT PROC
    PUSH BX
    PUSH CX
    PUSH SI
    PUSH DI
    PUSH BP
    MOV SI, DX
    MOV BP, AX
INSERT_LOOP:
    LODSB
    CMP AL, '$'
    JE INSERT_END
    CALL GET_CHILD
    CMP AX, 0
    JNE CHILD_EXISTS
    CALL CREATE_NODE
    CMP AX, 0
    JE INSERT_END
    MOV DX, AX
    MOV AL, [SI-1]
    CALL SET_CHILD
    MOV BP, DX
    JMP INSERT_LOOP
CHILD_EXISTS:
    MOV BP, AX
    JMP INSERT_LOOP
INSERT_END:
    MOV BYTE PTR [BP], 1
    POP BP
    POP DI
    POP SI
    POP CX
    POP BX
    RET
INSERT ENDP
SEARCH PROC
    PUSH BX
    PUSH SI
    PUSH BP
    MOV SI, DX
    MOV BP, AX
SEARCH_LOOP:
    LODSB
    CMP AL, '$'
    JE SEARCH_END
    CALL GET_CHILD
    CMP AX, 0
    JE SEARCH_NOTFOUND
    MOV BP, AX
    JMP SEARCH_LOOP
SEARCH_END:
    MOV AL, [BP]
    XOR AH, AH
    POP BP
    POP SI
    POP BX
    RET
SEARCH_NOTFOUND:
    XOR AX, AX
    POP BP
    POP SI
    POP BX
    RET
SEARCH ENDP
DELETE_FULL PROC
    PUSH BX
    PUSH CX
    PUSH SI
    PUSH DI
    PUSH BP
    MOV BYTE PTR [PATH_SP], 0
    MOV SI, DX
    MOV BP, AX
DEL_TRAV_LOOP:
    LODSB
    CMP AL, '$'
    JE DEL_TRAV_END
    MOV DL, AL
    SUB DL, 'A'
    CALL GET_CHILD
    CMP AX, 0
    JE DEL_NOTFOUND
    MOV BP, AX
    MOV AX, BP
    CALL PUSH_PATH
    JMP DEL_TRAV_LOOP
DEL_TRAV_END:
    CMP BYTE PTR [BP], 1
    JNE DEL_NOTFOUND
    MOV BYTE PTR [BP], 0
CLEANUP_LOOP:
    CALL POP_PATH
    CMP AX, 0
    JE CLEAN_DONE
    MOV BP, AX
    CALL HAS_CHILD
    CMP AX, 0
    JNE CLEAN_DONE
    CMP BYTE PTR [BP], 0
    JNE CLEAN_DONE
    CALL POP_PATH
    CMP AX, 0

    JE CLEAN_DONE
    MOV BP, AX
    MOV AL, 'A'
    ADD AL, BL
    XOR DX, DX
    CALL SET_CHILD
    MOV AX, BP
    MOV DL, 0FFH
    CALL PUSH_PATH
    JMP CLEANUP_LOOP
DEL_NOTFOUND:
    MOV BYTE PTR [PATH_SP], 0
    XOR AX, AX
    JMP DEL_FIN
CLEAN_DONE:
    MOV AX, 1
DEL_FIN:
    POP BP
    POP DI
    POP SI
    POP CX
    POP BX
    RET
DELETE_FULL ENDP
MAIN PROC
    MOV AX, @data
    MOV DS, AX
    MOV ES, AX
    CALL CREATE_NODE
    MOV BX, AX
    MOV DX, OFFSET WORD1
    MOV AX, BX
    CALL INSERT
    MOV DX, OFFSET MSG_INSERTED
    MOV AH, 09H
    INT 21H
    MOV DX, OFFSET WORD1
    MOV AH, 09H
    INT 21H
    MOV DX, OFFSET NEWLINE
    MOV AH, 09H
    INT 21H
    MOV DX, OFFSET WORD2
    MOV AX, BX
    CALL INSERT
    MOV DX, OFFSET WORD1
    MOV AX, BX
    CALL SEARCH
    CMP AX, 1
    JE PRINT_FOUND1
    MOV DX, OFFSET MSG_NOTFOUND
    MOV AH, 09H
    INT 21H
    JMP AFTER_SEARCH1
PRINT_FOUND1:
    MOV DX, OFFSET MSG_FOUND
    MOV AH, 09H
    INT 21H
AFTER_SEARCH1:
    MOV DX, OFFSET WORD1
    MOV AH, 09H
    INT 21H
    MOV DX, OFFSET NEWLINE
    MOV AH, 09H
    INT 21H
    MOV DX, OFFSET WORD1
    MOV AX, BX
    CALL DELETE_FULL
    CMP AX, 1
    JE PRINT_DELETED
    MOV DX, OFFSET MSG_NOTFOUND
    MOV AH, 09H
    INT 21H
    JMP AFTER_DEL
PRINT_DELETED:
    MOV DX, OFFSET MSG_DELETED
    MOV AH, 09H
    INT 21H
AFTER_DEL:
    MOV DX, OFFSET WORD1
    MOV AH, 09H
    INT 21H
    MOV DX, OFFSET NEWLINE
    MOV AH, 09H
    INT 21H
    MOV DX, OFFSET WORD1
    MOV AX, BX
    CALL SEARCH
    CMP AX, 1
    JE PRINT_FOUND2
    MOV DX, OFFSET MSG_NOTFOUND
    MOV AH, 09H
    INT 21H
    JMP END_PROG
PRINT_FOUND2:
    MOV DX, OFFSET MSG_FOUND
    MOV AH, 09H
    INT 21H
END_PROG:
    MOV DX, OFFSET WORD1
    MOV AH, 09H
    INT 21H
    MOV AH, 4CH
    INT 21H
MAIN ENDP
END MAIN
